import { useGLTF } from "@react-three/drei";
import { useRef } from "react";

export default function Cone({position}){
    const { nodes } = useGLTF('./models/cone.glb')
    const meshRef = useRef()
    
    return (
        <group position={position}>
            <mesh
                ref={(meshRef)}
                geometry={nodes.Cone01.geometry}
                scale={0.00005}
            >
                <meshStandardMaterial
                    visible={false}
                />
            </mesh>
            <mesh
                ref={(meshRef)}
                geometry={nodes.Cone02.geometry}
                scale={0.00005}
            >
                <meshStandardMaterial
                    visible={false}
                />
            </mesh>
            <mesh
                ref={(meshRef)}
                geometry={nodes.Cone03.geometry}
                scale={0.00005}
            >
                <meshStandardMaterial
                    visible={false}
                />
            </mesh>
            <mesh
                ref={(meshRef)}
                geometry={nodes.Cone04.geometry}
                scale={0.00005}
            >
                <meshStandardMaterial
                    visible={false}
                />
            </mesh>
            <mesh
                ref={(meshRef)}
                geometry={nodes.Cone05.geometry}
                scale={0.00005}
            >
                <meshStandardMaterial
                    visible={false}
                />
            </mesh>
            <mesh
                ref={(meshRef)}
                geometry={nodes.Cone06.geometry}
                scale={0.00005}
            >
                <meshStandardMaterial
                    visible={false}
                />
            </mesh>
            <mesh
                ref={(meshRef)}
                geometry={nodes.Cone07.geometry}
                scale={0.00005}
            >
                <meshStandardMaterial
                    visible={false}
                />
            </mesh>
            <mesh
                ref={(meshRef)}
                geometry={nodes.Cone08.geometry}
                scale={0.00005}
            >
                <meshStandardMaterial
                    visible={false}
                />
            </mesh>
            <mesh
                ref={(meshRef)}
                geometry={nodes.Cone09.geometry}
                scale={0.00005}
            >
                <meshStandardMaterial
                    visible={false}
                />
            </mesh>
            <mesh
                ref={(meshRef)}
                geometry={nodes.Cone10.geometry}
                scale={0.00005}
            >
                <meshStandardMaterial
                    visible={false}
                />
            </mesh>
            <mesh
                ref={(meshRef)}
                geometry={nodes.Cone11.geometry}
                scale={0.00005}
            >
                <meshStandardMaterial
                    visible={false}
                />
            </mesh>
            <mesh
                ref={(meshRef)}
                geometry={nodes.Cone12.geometry}
                scale={0.00005}
            >
                <meshStandardMaterial
                    visible={false}
                />
            </mesh>
        </group>
    )
}