import { useGLTF } from "@react-three/drei";

export default function Distributeur({ref}){
    const { nodes } = useGLTF('./models/distributeur.glb')
console.log("ok", ref)
    return (
        <group>
            <mesh
                ref={ref}
                geometry={nodes.plank.geometry}
                scale={0.00005}
            >
                <meshStandardMaterial
                    visible={false}
                />
            </mesh>
            <mesh
                ref={ref}
                geometry={nodes.Cylinder01.geometry}
                scale={0.00005}
            >
                <meshStandardMaterial
                    visible={false}
                />
            </mesh>
            <mesh
                ref={ref}
                geometry={nodes.Cylinder02.geometry}
                scale={0.00005}
            >
                <meshStandardMaterial
                    visible={false}
                />
            </mesh>
            <mesh
                ref={ref}
                geometry={nodes.Cylinder03.geometry}
                scale={0.00005}
            >
                <meshStandardMaterial
                    visible={false}
                />
            </mesh>
            <mesh
                ref={ref}
                geometry={nodes.Cylinder04.geometry}
                scale={0.00005}
            >
                <meshStandardMaterial
                    visible={false}
                />
            </mesh>
            <mesh
                ref={ref}
                geometry={nodes.Cylinder05.geometry}
                scale={0.00005}
            >
                <meshStandardMaterial
                    visible={false}
                />
            </mesh>
            <mesh
                ref={ref}
                geometry={nodes.Cylinder06.geometry}
                scale={0.00005}
            >
                <meshStandardMaterial
                    visible={false}
                />
            </mesh>
            <mesh
                ref={ref}
                geometry={nodes.Cylinder07.geometry}
                scale={0.00005}
            >
                <meshStandardMaterial
                    visible={false}
                />
            </mesh>
            <mesh
                ref={ref}
                geometry={nodes.Cylinder08.geometry}
                scale={0.00005}
            >
                <meshStandardMaterial
                    visible={false}
                />
            </mesh>
            <mesh
                ref={ref}
                geometry={nodes.Cylinder09.geometry}
                scale={0.00005}
            >
                <meshStandardMaterial
                    visible={false}
                />
            </mesh>
            
        </group>
    )
}